"use client";

import { useState, useEffect } from "react";
import { ExplanationSkeleton } from "./LoadingSkeleton";
import { cn } from "@/lib/utils";

type Level = "beginner" | "intermediate" | "advanced";

const LEVELS: { key: Level; label: string; description: string }[] = [
  { key: "beginner", label: "Beginner", description: "Simple language, analogies, no jargon" },
  { key: "intermediate", label: "Intermediate", description: "Moderate technical depth" },
  { key: "advanced", label: "Advanced", description: "Full technical depth for researchers" },
];

interface ExplanationTabsProps {
  paperId: string;
}

interface ExplanationState {
  content: string;
  model: string;
  cached: boolean;
}

export function ExplanationTabs({ paperId }: ExplanationTabsProps) {
  const [activeLevel, setActiveLevel] = useState<Level>("beginner");
  const [explanations, setExplanations] = useState<Partial<Record<Level, ExplanationState>>>({});
  const [loading, setLoading] = useState<Partial<Record<Level, boolean>>>({});
  const [errors, setErrors] = useState<Partial<Record<Level, string>>>({});

  const loadExplanation = async (level: Level) => {
    if (explanations[level] || loading[level]) return;

    setLoading((prev) => ({ ...prev, [level]: true }));
    setErrors((prev) => ({ ...prev, [level]: undefined }));

    try {
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ paperId, level }),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      const data = await res.json() as { explanation: { content: string; model: string }; cached: boolean };
      setExplanations((prev) => ({
        ...prev,
        [level]: {
          content: data.explanation.content,
          model: data.explanation.model,
          cached: data.cached,
        },
      }));
    } catch (err) {
      console.error(err);
      setErrors((prev) => ({
        ...prev,
        [level]: "Failed to generate explanation. Please try again.",
      }));
    } finally {
      setLoading((prev) => ({ ...prev, [level]: false }));
    }
  };

  const handleTabClick = (level: Level) => {
    setActiveLevel(level);
    loadExplanation(level);
  };

  // Auto-load beginner on mount
  useEffect(() => {
    loadExplanation("beginner");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const current = explanations[activeLevel];
  const isLoading = loading[activeLevel];
  const error = errors[activeLevel];

  return (
    <div className="mt-8">
      <h2 className="text-xl font-semibold text-gray-900 mb-4">Explanation</h2>

      {/* Tab buttons */}
      <div className="flex gap-1 p-1 bg-gray-100 rounded-xl w-fit mb-6">
        {LEVELS.map(({ key, label }) => (
          <button
            key={key}
            onClick={() => handleTabClick(key)}
            className={cn(
              "px-4 py-2 rounded-lg text-sm font-medium transition-all",
              activeLevel === key
                ? "bg-white text-blue-600 shadow-sm"
                : "text-gray-500 hover:text-gray-700"
            )}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Level description */}
      <p className="text-sm text-gray-400 mb-4 italic">
        {LEVELS.find((l) => l.key === activeLevel)?.description}
      </p>

      {/* Content area */}
      <div className="min-h-[200px]">
        {isLoading && <ExplanationSkeleton />}

        {error && !isLoading && (
          <div className="p-4 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
            {error}
            <button
              onClick={() => {
                setErrors((prev) => ({ ...prev, [activeLevel]: undefined }));
                loadExplanation(activeLevel);
              }}
              className="ml-3 underline hover:no-underline"
            >
              Retry
            </button>
          </div>
        )}

        {current && !isLoading && (
          <div className="space-y-1">
            <div
              className="prose prose-sm prose-gray max-w-none text-gray-800 leading-relaxed"
              dangerouslySetInnerHTML={{ __html: markdownToHtml(current.content) }}
            />
            <p className="text-xs text-gray-300 mt-6 pt-4 border-t border-gray-100">
              Generated by <span className="font-mono">{current.model}</span>
              {current.cached && " · cached"}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

// Minimal markdown renderer (headings, bold, newlines) — no external deps needed
function markdownToHtml(md: string): string {
  return md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/^## (.+)$/gm, '<h2 class="text-lg font-semibold text-gray-900 mt-6 mb-2">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-semibold text-gray-800 mt-4 mb-1">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code class="text-xs bg-gray-100 px-1 py-0.5 rounded font-mono">$1</code>')
    .replace(/\n\n/g, '</p><p class="mb-3">')
    .replace(/^(.)/m, '<p class="mb-3">$1')
    .replace(/$/, "</p>");
}
