import { prisma } from "./prisma";

interface SeedPaper {
  arxivId: string;
  title: string;
  summary: string;
  authors: string[];
  publishedAt: Date;
  pdfUrl: string;
  categories: string[];
}

const MUST_READ_PAPERS: SeedPaper[] = [
  {
    arxivId: "1706.03762",
    title: "Attention Is All You Need",
    summary: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train.",
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N. Gomez", "Lukasz Kaiser", "Illia Polosukhin"],
    publishedAt: new Date("2017-06-12"),
    pdfUrl: "https://arxiv.org/pdf/1706.03762",
    categories: ["cs.CL", "cs.LG"],
  },
  {
    arxivId: "1810.04805",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    summary: "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks.",
    authors: ["Jacob Devlin", "Ming-Wei Chang", "Kenton Lee", "Kristina Toutanova"],
    publishedAt: new Date("2018-10-11"),
    pdfUrl: "https://arxiv.org/pdf/1810.04805",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2005.14165",
    title: "Language Models are Few-Shot Learners (GPT-3)",
    summary: "We demonstrate that scaling language models greatly improves task-agnostic, few-shot performance, sometimes even reaching competitiveness with prior state-of-the-art fine-tuning approaches. Specifically, we train GPT-3, an autoregressive language model with 175 billion parameters, 10x more than any previous non-sparse language model, and test its performance in the few-shot setting.",
    authors: ["Tom B. Brown", "Benjamin Mann", "Nick Ryder", "Melanie Subbiah", "Jared Kaplan", "Prafulla Dhariwal", "Arvind Neelakantan", "Pranav Shyam", "Girish Sastry", "Amanda Askell", "Sandhini Agarwal", "Ariel Herbert-Voss", "Gretchen Krueger", "Tom Henighan", "Rewon Child", "Aditya Ramesh", "Daniel M. Ziegler", "Jeffrey Wu", "Clemens Winter", "Christopher Hesse", "Mark Chen", "Eric Sigler", "Mateusz Litwin", "Scott Gray", "Benjamin Chess", "Jack Clark", "Christopher Berner", "Sam McCandlish", "Alec Radford", "Ilya Sutskever", "Dario Amodei"],
    publishedAt: new Date("2020-05-28"),
    pdfUrl: "https://arxiv.org/pdf/2005.14165",
    categories: ["cs.CL"],
  },
  {
    arxivId: "1512.03385",
    title: "Deep Residual Learning for Image Recognition",
    summary: "We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth.",
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    publishedAt: new Date("2015-12-10"),
    pdfUrl: "https://arxiv.org/pdf/1512.03385",
    categories: ["cs.CV"],
  },
  {
    arxivId: "1406.2661",
    title: "Generative Adversarial Networks",
    summary: "We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G. The training procedure for G is to maximize the probability of D making a mistake.",
    authors: ["Ian J. Goodfellow", "Jean Pouget-Abadie", "Mehdi Mirza", "Bing Xu", "David Warde-Farley", "Sherjil Ozair", "Aaron Courville", "Yoshua Bengio"],
    publishedAt: new Date("2014-06-10"),
    pdfUrl: "https://arxiv.org/pdf/1406.2661",
    categories: ["cs.LG", "stat.ML"],
  },
  {
    arxivId: "1412.6980",
    title: "Adam: A Method for Stochastic Optimization",
    summary: "We introduce Adam, an algorithm for first-order gradient-based optimization of stochastic objective functions, based on adaptive estimates of lower-order moments. The method is straightforward to implement, is computationally efficient, has little memory requirements, is invariant to diagonal rescaling of the gradients, and is well suited for problems that are large in terms of data and/or parameters.",
    authors: ["Diederik P. Kingma", "Jimmy Ba"],
    publishedAt: new Date("2014-12-22"),
    pdfUrl: "https://arxiv.org/pdf/1412.6980",
    categories: ["cs.LG"],
  },
  {
    arxivId: "1502.03167",
    title: "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift",
    summary: "Training Deep Neural Networks is complicated by the fact that the distribution of each layer's inputs changes during training, as the parameters of the previous layers change. We refer to this phenomenon as internal covariate shift, and address the problem by normalizing layer inputs. Our method draws its strength from making normalization a part of the model architecture and performing the normalization for each training mini-batch.",
    authors: ["Sergey Ioffe", "Christian Szegedy"],
    publishedAt: new Date("2015-02-11"),
    pdfUrl: "https://arxiv.org/pdf/1502.03167",
    categories: ["cs.LG"],
  },
  {
    arxivId: "2010.11929",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale (ViT)",
    summary: "While the Transformer architecture has become the de-facto standard for natural language processing tasks, its applications to computer vision remain limited. In vision, attention is either applied in conjunction with convolutional networks, or used to replace certain components of convolutional networks while keeping their overall structure in place. We show that this reliance on CNNs is not necessary and a pure transformer applied directly to sequences of image patches can perform very well on image classification tasks.",
    authors: ["Alexey Dosovitskiy", "Lucas Beyer", "Alexander Kolesnikov", "Dirk Weissenborn", "Xiaohua Zhai", "Thomas Unterthiner", "Mostafa Dehghani", "Matthias Minderer", "Georg Heigold", "Sylvain Gelly", "Jakob Uszkoreit", "Neil Houlsby"],
    publishedAt: new Date("2020-10-22"),
    pdfUrl: "https://arxiv.org/pdf/2010.11929",
    categories: ["cs.CV", "cs.AI", "cs.LG"],
  },
  {
    arxivId: "2103.00020",
    title: "Learning Transferable Visual Models From Natural Language Supervision (CLIP)",
    summary: "State-of-the-art computer vision systems are trained to predict a fixed set of predetermined object categories. This restricted form of supervision limits their generality and usability since additional labeled data is needed to specify any other visual concept. Learning directly from raw text about images is a promising alternative which leverages a much broader source of supervision. We demonstrate that the simple pre-training task of predicting which caption goes with which image is an efficient and scalable way to learn SOTA image representations from scratch.",
    authors: ["Alec Radford", "Jong Wook Kim", "Chris Hallacy", "Aditya Ramesh", "Gabriel Goh", "Sandhini Agarwal", "Girish Sastry", "Amanda Askell", "Pamela Mishkin", "Jack Clark", "Gretchen Krueger", "Ilya Sutskever"],
    publishedAt: new Date("2021-02-26"),
    pdfUrl: "https://arxiv.org/pdf/2103.00020",
    categories: ["cs.CV", "cs.LG"],
  },
  {
    arxivId: "2112.10752",
    title: "High-Resolution Image Synthesis with Latent Diffusion Models (Stable Diffusion)",
    summary: "By decomposing the image formation process into a sequential application of denoising autoencoders, diffusion models (DMs) achieve state-of-the-art synthesis results on image data and beyond. Additionally, their formulation allows for a guiding mechanism to control the image generation process without retraining. However, since these models operate directly in pixel space, optimization of powerful DMs often consumes hundreds of GPU days and inference is expensive due to sequential evaluations.",
    authors: ["Robin Rombach", "Andreas Blattmann", "Dominik Lorenz", "Patrick Esser", "Björn Ommer"],
    publishedAt: new Date("2021-12-20"),
    pdfUrl: "https://arxiv.org/pdf/2112.10752",
    categories: ["cs.CV", "cs.LG"],
  },
  {
    arxivId: "2006.11239",
    title: "Denoising Diffusion Probabilistic Models (DDPM)",
    summary: "We present high quality image synthesis results using diffusion probabilistic models, a class of latent variable models inspired by considerations from nonequilibrium thermodynamics. Our best results are obtained by training on a weighted variational bound designed according to a novel connection between diffusion probabilistic models and denoising score matching with Langevin dynamics, and our models naturally admit a progressive lossy decompression scheme.",
    authors: ["Jonathan Ho", "Ajay Jain", "Pieter Abbeel"],
    publishedAt: new Date("2020-06-19"),
    pdfUrl: "https://arxiv.org/pdf/2006.11239",
    categories: ["cs.LG", "stat.ML"],
  },
  {
    arxivId: "2203.02155",
    title: "Training language models to follow instructions with human feedback (InstructGPT)",
    summary: "Making language models bigger does not inherently make them better at following a user's intent. Large language models can generate outputs that are untruthful, toxic, or simply not helpful to the user. We show an avenue for aligning language models with user intent on a wide range of tasks by fine-tuning with human feedback. Starting with a set of labeler-written prompts, we use reinforcement learning from human feedback to fine-tune GPT-3 to follow instructions.",
    authors: ["Long Ouyang", "Jeff Wu", "Xu Jiang", "Diogo Almeida", "Carroll L. Wainwright", "Pamela Mishkin", "Chong Zhang", "Sandhini Agarwal", "Katarina Slama", "Alex Ray", "John Schulman", "Jacob Hilton", "Fraser Kelton", "Luke Miller", "Maddie Simens", "Amanda Askell", "Peter Welinder", "Paul Christiano", "Jan Leike", "Ryan Lowe"],
    publishedAt: new Date("2022-03-04"),
    pdfUrl: "https://arxiv.org/pdf/2203.02155",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2302.13971",
    title: "LLaMA: Open and Efficient Foundation Language Models",
    summary: "We introduce LLaMA, a collection of foundation language models ranging from 7B to 65B parameters. We train our models on trillions of tokens, and show that it is possible to train state-of-the-art models using publicly available datasets exclusively, without resorting to proprietary and inaccessible datasets. In particular, LLaMA-13B outperforms GPT-3 (175B) on most benchmarks.",
    authors: ["Hugo Touvron", "Thibaut Lavril", "Gautier Izacard", "Xavier Martinet", "Marie-Anne Lachaux", "Timothée Lacroix", "Baptiste Rozière", "Naman Goyal", "Eric Hambro", "Faisal Azhar", "Aurelien Rodriguez", "Armand Joulin", "Edouard Grave", "Guillaume Lample"],
    publishedAt: new Date("2023-02-27"),
    pdfUrl: "https://arxiv.org/pdf/2302.13971",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2307.09288",
    title: "Llama 2: Open Foundation and Fine-Tuned Chat Models",
    summary: "We develop and release Llama 2, a collection of pretrained and fine-tuned large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters. Our fine-tuned LLMs, called Llama 2-Chat, are optimized for dialogue use cases. Our models outperform open-source chat models on most benchmarks we tested, and based on our human evaluations for helpfulness and safety, may be a suitable substitute for closed-source models.",
    authors: ["Hugo Touvron", "Louis Martin", "Kevin Stone", "Peter Albert", "Amjad Almahairi", "Yasmine Babaei", "Nikolay Bashlykov", "Soumya Batra", "Prajjwal Bhargava", "Shruti Bhosale"],
    publishedAt: new Date("2023-07-18"),
    pdfUrl: "https://arxiv.org/pdf/2307.09288",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2201.11903",
    title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
    summary: "We explore how generating a chain of thought — a series of intermediate reasoning steps — significantly improves the ability of large language models to perform complex reasoning. In particular, we show how such reasoning abilities emerge naturally in sufficiently large language models via a simple method called chain-of-thought prompting, where a few chain of thought demonstrations are provided as exemplars in prompting.",
    authors: ["Jason Wei", "Xuezhi Wang", "Dale Schuurmans", "Maarten Bosma", "Brian Ichter", "Fei Xia", "Ed Chi", "Quoc Le", "Denny Zhou"],
    publishedAt: new Date("2022-01-28"),
    pdfUrl: "https://arxiv.org/pdf/2201.11903",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2106.09685",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    summary: "An important paradigm of natural language processing consists of large-scale pre-training on general domain data and adaptation to particular tasks or domains. As we pre-train larger models, full fine-tuning, which retrains all model parameters, becomes less feasible. We propose Low-Rank Adaptation, or LoRA, which freezes the pretrained model weights and injects trainable rank decomposition matrices into each layer of the Transformer architecture, greatly reducing the number of trainable parameters for downstream tasks.",
    authors: ["Edward J. Hu", "Yelong Shen", "Phillip Wallis", "Zeyuan Allen-Zhu", "Yuanzhi Li", "Shean Wang", "Lu Wang", "Weizhu Chen"],
    publishedAt: new Date("2021-06-17"),
    pdfUrl: "https://arxiv.org/pdf/2106.09685",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2205.14135",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    summary: "Transformers are slow and memory-hungry on long sequences, since the time and memory complexity of self-attention are quadratic in sequence length. Approximate attention methods have attempted to address this problem, but often do not achieve wall-clock speedup. We argue that a missing principle is making attention algorithms IO-aware — accounting for reads and writes between levels of GPU memory. We propose FlashAttention, an IO-aware exact attention algorithm that uses tiling to reduce the number of memory reads/writes between GPU high bandwidth memory and on-chip SRAM.",
    authors: ["Tri Dao", "Daniel Y. Fu", "Stefano Ermon", "Atri Rudra", "Christopher Ré"],
    publishedAt: new Date("2022-05-27"),
    pdfUrl: "https://arxiv.org/pdf/2205.14135",
    categories: ["cs.LG"],
  },
  {
    arxivId: "1707.06347",
    title: "Proximal Policy Optimization Algorithms (PPO)",
    summary: "We propose a new family of policy gradient methods for reinforcement learning, which alternate between sampling data through interaction with the environment, and optimizing a 'surrogate' objective function using stochastic gradient ascent. Whereas standard policy gradient methods perform one gradient update per data sample, we propose a novel objective function that enables multiple epochs of minibatch updates.",
    authors: ["John Schulman", "Filip Wolski", "Prafulla Dhariwal", "Alec Radford", "Oleg Klimov"],
    publishedAt: new Date("2017-07-20"),
    pdfUrl: "https://arxiv.org/pdf/1707.06347",
    categories: ["cs.LG"],
  },
  {
    arxivId: "2212.08073",
    title: "Constitutional AI: Harmlessness from AI Feedback",
    summary: "As AI systems become more capable, we would like to enlist their help to supervise other AIs. We experiment with methods for training a harmless AI assistant through self-improvement, without any human labels identifying harmful outputs. The only human oversight is provided through a list of rules or principles, and so we call the method Constitutional AI.",
    authors: ["Yuntao Bai", "Saurav Kadavath", "Sandipan Kundu", "Amanda Askell", "Jackson Kernion", "Andy Jones", "Anna Chen", "Anna Goldie", "Azalia Mirhoseini", "Cameron McKinnon"],
    publishedAt: new Date("2022-12-15"),
    pdfUrl: "https://arxiv.org/pdf/2212.08073",
    categories: ["cs.AI", "cs.CL"],
  },
  {
    arxivId: "2110.07602",
    title: "Scaling Language Models: Methods, Analysis & Insights from Training Gopher",
    summary: "Language modelling provides a step towards intelligent communication systems by giving machines the ability to process and generate text. In this paper, we present an analysis of transformer-based language model performance across a wide range of model scales — from models with tens of millions of parameters up to a 280 billion parameter model called Gopher.",
    authors: ["Jack W. Rae", "Sebastian Borgeaud", "Trevor Cai", "Katie Millican", "Jordan Hoffmann", "Francis Song", "John Aslanides", "Sarah Henderson", "Roman Ring", "Susannah Young"],
    publishedAt: new Date("2021-12-08"),
    pdfUrl: "https://arxiv.org/pdf/2110.07602",
    categories: ["cs.CL", "cs.LG"],
  },
  {
    arxivId: "2303.08774",
    title: "GPT-4 Technical Report",
    summary: "We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs. Although less capable than humans in many real-world scenarios, GPT-4 exhibits human-level performance on various professional and academic benchmarks. For example, it passes a simulated bar exam with a score around the top 10% of test takers.",
    authors: ["OpenAI"],
    publishedAt: new Date("2023-03-15"),
    pdfUrl: "https://arxiv.org/pdf/2303.08774",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "1207.0580",
    title: "Improving neural networks by preventing co-adaptation of feature detectors (Dropout)",
    summary: "When a large feedforward neural network is trained on a small training set, it typically performs poorly on held-out test data. This overfitting is greatly reduced by randomly omitting half of the feature detectors on each training case. This prevents complex co-adaptations in which a feature detector is only helpful in the context of several other specific feature detectors.",
    authors: ["Geoffrey E. Hinton", "Nitish Srivastava", "Alex Krizhevsky", "Ilya Sutskever", "Ruslan R. Salakhutdinov"],
    publishedAt: new Date("2012-07-03"),
    pdfUrl: "https://arxiv.org/pdf/1207.0580",
    categories: ["cs.NE", "cs.LG"],
  },
  {
    arxivId: "1301.3666",
    title: "Efficient Estimation of Word Representations in Vector Space (Word2Vec)",
    summary: "We propose two novel model architectures for computing continuous vector representations of words from very large data sets. The quality of these representations is measured in a word similarity task, and the results are compared to the previously best performing techniques based on different types of neural networks.",
    authors: ["Tomas Mikolov", "Kai Chen", "Greg Corrado", "Jeffrey Dean"],
    publishedAt: new Date("2013-01-16"),
    pdfUrl: "https://arxiv.org/pdf/1301.3666",
    categories: ["cs.CL"],
  },
  {
    arxivId: "1409.0473",
    title: "Neural Machine Translation by Jointly Learning to Align and Translate (Bahdanau Attention)",
    summary: "Neural machine translation is a recently proposed approach to machine translation. We conjecture that the use of a fixed-length vector is a bottleneck in improving the performance of this basic encoder-decoder architecture, and propose to extend this by allowing a model to automatically (soft-)search for parts of a source sentence that are relevant to predicting a target word.",
    authors: ["Dzmitry Bahdanau", "Kyunghyun Cho", "Yoshua Bengio"],
    publishedAt: new Date("2014-09-01"),
    pdfUrl: "https://arxiv.org/pdf/1409.0473",
    categories: ["cs.CL", "cs.LG", "cs.NE", "stat.ML"],
  },
  {
    arxivId: "1409.1556",
    title: "Very Deep Convolutional Networks for Large-Scale Image Recognition (VGGNet)",
    summary: "In this work we investigate the effect of the convolutional network depth on its accuracy in the large-scale image recognition setting. Our main contribution is a thorough evaluation of networks of increasing depth using an architecture with very small (3×3) convolution filters, which shows that a significant improvement on the prior-art configurations can be achieved by pushing the depth to 16–19 weight layers.",
    authors: ["Karen Simonyan", "Andrew Zisserman"],
    publishedAt: new Date("2014-09-04"),
    pdfUrl: "https://arxiv.org/pdf/1409.1556",
    categories: ["cs.CV"],
  },
  {
    arxivId: "1608.06993",
    title: "Densely Connected Convolutional Networks (DenseNet)",
    summary: "Recent work has shown that convolutional networks can be substantially deeper, more accurate, and efficient to train if they contain shorter connections between layers close to the input and those close to the output. In this paper, we embrace this observation and introduce the Dense Convolutional Network (DenseNet), which connects each layer to every other layer in a feed-forward fashion.",
    authors: ["Gao Huang", "Zhuang Liu", "Laurens van der Maaten", "Kilian Q. Weinberger"],
    publishedAt: new Date("2016-08-25"),
    pdfUrl: "https://arxiv.org/pdf/1608.06993",
    categories: ["cs.CV", "cs.LG"],
  },
  {
    arxivId: "1907.11692",
    title: "RoBERTa: A Robustly Optimized BERT Pretraining Approach",
    summary: "Language model pretraining has led to significant performance gains but careful comparison between different approaches is challenging. We present a replication study of BERT pretraining that carefully measures the impact of many key hyperparameters and training data size. We find that BERT was significantly undertrained and can match or exceed every model published after it.",
    authors: ["Yinhan Liu", "Myle Ott", "Naman Goyal", "Jingfei Du", "Mandar Joshi", "Danqi Chen", "Omer Levy", "Mike Lewis", "Luke Zettlemoyer", "Veselin Stoyanov"],
    publishedAt: new Date("2019-07-26"),
    pdfUrl: "https://arxiv.org/pdf/1907.11692",
    categories: ["cs.CL"],
  },
  {
    arxivId: "1910.10683",
    title: "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer (T5)",
    summary: "Transfer learning, where a model is first pre-trained on a data-rich task before being fine-tuned on a downstream task, has emerged as a powerful technique in natural language processing. In this paper, we explore the landscape of transfer learning techniques for NLP by introducing a unified framework that converts every language problem into a text-to-text format.",
    authors: ["Colin Raffel", "Noam Shazeer", "Adam Roberts", "Katherine Lee", "Sharan Narang", "Michael Matena", "Yanqi Zhou", "Wei Li", "Peter J. Liu"],
    publishedAt: new Date("2019-10-23"),
    pdfUrl: "https://arxiv.org/pdf/1910.10683",
    categories: ["cs.LG", "cs.CL"],
  },
  {
    arxivId: "2005.11401",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks (RAG)",
    summary: "Large pre-trained language models store factual knowledge in their parameters and achieve state-of-the-art results when fine-tuned on downstream NLP tasks. However, their ability to access and precisely manipulate knowledge is still limited. We explore a general-purpose fine-tuning recipe for retrieval-augmented generation — models which combine pre-trained parametric and non-parametric memory for language generation.",
    authors: ["Patrick Lewis", "Ethan Perez", "Aleksandra Piktus", "Fabio Petroni", "Vladimir Karpukhin", "Naman Goyal", "Heinrich Küttler", "Mike Lewis", "Wen-tau Yih", "Tim Rocktäschel", "Sebastian Riedel", "Douwe Kiela"],
    publishedAt: new Date("2020-05-22"),
    pdfUrl: "https://arxiv.org/pdf/2005.11401",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2109.01652",
    title: "Finetuned Language Models Are Zero-Shot Learners (FLAN)",
    summary: "This paper explores a simple method for improving the zero-shot learning abilities of language models. We show that instruction tuning — finetuning language models on a collection of tasks described via instructions — substantially improves zero-shot performance on unseen tasks.",
    authors: ["Jason Wei", "Maarten Bosma", "Vincent Y. Zhao", "Kelvin Guu", "Adams Wei Yu", "Brian Lester", "Nan Du", "Andrew M. Dai", "Quoc V. Le"],
    publishedAt: new Date("2021-09-03"),
    pdfUrl: "https://arxiv.org/pdf/2109.01652",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2302.07459",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    summary: "Language models (LMs) exhibit remarkable abilities to solve new tasks from just a few examples or textual instructions, especially at scale. We show that LMs can teach themselves to use external tools via simple APIs and achieve the best of both worlds by introducing Toolformer, a model trained to decide which APIs to call, when to call them, what arguments to pass, and how to best incorporate the results into future token prediction.",
    authors: ["Timo Schick", "Jane Dwivedi-Yu", "Roberto Dessì", "Roberta Raileanu", "Maria Lomeli", "Luke Zettlemoyer", "Nicola Cancedda", "Thomas Scialom"],
    publishedAt: new Date("2023-02-09"),
    pdfUrl: "https://arxiv.org/pdf/2302.07459",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2310.06825",
    title: "Mistral 7B",
    summary: "We introduce Mistral 7B, a 7-billion-parameter language model engineered for superior performance and efficiency. Mistral 7B outperforms the best open 13B model (Llama 2 13B) across all evaluated benchmarks, and the best released 34B model (Llama 1 34B) in reasoning, mathematics, and code generation. Using Grouped-query attention (GQA) for faster inference, and Sliding Window Attention (SWA) to handle longer sequences at smaller cost.",
    authors: ["Albert Q. Jiang", "Alexandre Sablayrolles", "Arthur Mensch", "Chris Bamford", "Devendra Singh Chaplot", "Diego de las Casas", "Florian Bressand", "Gianna Lengyel", "Guillaume Lample", "Lucile Saulnier", "Lélio Renard Lavaud", "Marie-Anne Lachaux", "Pierre Stock", "Teven Le Scao", "Thibaut Lavril", "Thomas Wang", "Timothée Lacroix", "William El Sayed"],
    publishedAt: new Date("2023-10-10"),
    pdfUrl: "https://arxiv.org/pdf/2310.06825",
    categories: ["cs.CL", "cs.LG"],
  },
  {
    arxivId: "2401.04088",
    title: "Mixtral of Experts",
    summary: "We introduce Mixtral 8x7B, a Sparse Mixture of Experts (SMoE) language model. Mixtral has the same architecture as Mistral 7B, with the difference that each layer is composed of 8 feedforward blocks (i.e. experts). A router network selects two experts to process the current state for each token at each layer. Mixtral outperforms Llama 2 70B and GPT-3.5 across all benchmarks.",
    authors: ["Albert Q. Jiang", "Alexandre Sablayrolles", "Antoine Roux", "Arthur Mensch", "Blanche Savary", "Chris Bamford", "Devendra Singh Chaplot", "Diego de las Casas", "Emma Bonta Pernic"],
    publishedAt: new Date("2024-01-08"),
    pdfUrl: "https://arxiv.org/pdf/2401.04088",
    categories: ["cs.LG", "cs.CL"],
  },
  {
    arxivId: "2312.11805",
    title: "Gemini: A Family of Highly Capable Multimodal Models",
    summary: "This report introduces a new family of multimodal models, Gemini, that demonstrate remarkable capabilities across image, audio, video, and text understanding. The Gemini family consists of Ultra, Pro, and Nano sizes, suitable for applications ranging from complex reasoning tasks to on-device memory-constrained use-cases. Gemini Ultra achieves human-expert performance on MMLU and state-of-the-art on 30 of 32 benchmarks.",
    authors: ["Gemini Team Google"],
    publishedAt: new Date("2023-12-19"),
    pdfUrl: "https://arxiv.org/pdf/2312.11805",
    categories: ["cs.CL", "cs.AI", "cs.CV"],
  },
  {
    arxivId: "2312.00752",
    title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
    summary: "Foundation models, now powering most of the exciting applications in deep learning, are almost universally based on the Transformer architecture and its core attention module. Many subquadratic-time architectures such as linear attention, gated convolution and recurrent models, and structured state space models (SSMs) have been developed to address Transformers' computational inefficiency on long sequences. Mamba is a new state space model architecture showing promising performance on information-dense data such as language modeling, where previous sub-quadratic models fall short of Transformers.",
    authors: ["Albert Gu", "Tri Dao"],
    publishedAt: new Date("2023-12-01"),
    pdfUrl: "https://arxiv.org/pdf/2312.00752",
    categories: ["cs.LG"],
  },
  {
    arxivId: "2501.12948",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    summary: "We introduce DeepSeek-R1, which uses reinforcement learning to incentivize reasoning in large language models. DeepSeek-R1-Zero, trained purely via RL without supervised fine-tuning, demonstrates strong reasoning capabilities. DeepSeek-R1 achieves performance comparable to OpenAI-o1 on math, code, and reasoning benchmarks.",
    authors: ["DeepSeek-AI"],
    publishedAt: new Date("2025-01-20"),
    pdfUrl: "https://arxiv.org/pdf/2501.12948",
    categories: ["cs.CL", "cs.AI", "cs.LG"],
  },
  {
    arxivId: "2001.08361",
    title: "Scaling Laws for Neural Language Models",
    summary: "We study empirical scaling laws for language model performance on the cross-entropy loss. The loss scales as a power-law with model size, dataset size, and the amount of compute used for training, with some trends spanning more than seven orders of magnitude. Other architectural details such as network width or depth have minimal effects within a wide range.",
    authors: ["Jared Kaplan", "Sam McCandlish", "Tom Henighan", "Tom B. Brown", "Benjamin Chess", "Rewon Child", "Scott Gray", "Alec Radford", "Jeffrey Wu", "Dario Amodei"],
    publishedAt: new Date("2020-01-23"),
    pdfUrl: "https://arxiv.org/pdf/2001.08361",
    categories: ["cs.LG", "stat.ML"],
  },
  {
    arxivId: "2203.15556",
    title: "Training Compute-Optimal Large Language Models (Chinchilla)",
    summary: "We investigate the optimal model size and number of tokens for training a transformer language model under a given compute budget. We find that current large language models are significantly undertrained. For compute-optimal training, the model size and the number of training tokens should be scaled equally.",
    authors: ["Jordan Hoffmann", "Sebastian Borgeaud", "Arthur Mensch", "Elena Buchatskaya", "Trevor Cai", "Eliza Rutherford", "Diego de las Casas", "Lisa Anne Hendrycks", "Johannes Welbl", "Aidan Clark", "Tom Hennigan", "Eric Noland", "Katie Millican", "George van den Driessche", "Bogdan Damoc", "Aurelia Guy", "Simon Osindero", "Karen Simonyan", "Erich Elsen", "Jack W. Rae", "Oriol Vinyals", "Laurent Sifre"],
    publishedAt: new Date("2022-03-29"),
    pdfUrl: "https://arxiv.org/pdf/2203.15556",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2204.02311",
    title: "PaLM: Scaling Language Modeling with Pathways",
    summary: "We introduce PaLM, a 540-billion parameter, densely activated, Transformer language model, which achieves strong performance across a wide range of language tasks and reasoning tasks. We train PaLM on 6144 TPU v4 chips using Pathways, a new ML system which enables highly efficient training across multiple TPU Pods.",
    authors: ["Aakanksha Chowdhery", "Sharan Narang", "Jacob Devlin", "Maarten Bosma", "Gaurav Mishra", "Adam Roberts", "Paul Barham", "Hyung Won Chung", "Charles Sutton", "Sebastian Gehrmann"],
    publishedAt: new Date("2022-04-05"),
    pdfUrl: "https://arxiv.org/pdf/2204.02311",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2210.03629",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    summary: "We explore the use of LLMs to generate both reasoning traces and task-specific actions in an interleaved manner. ReAct prompts LLMs to generate verbal reasoning traces and actions, allowing the model to induce, track, and update action plans as well as handle exceptions — enabling the model to interact with external information sources.",
    authors: ["Shunyu Yao", "Jeffrey Zhao", "Dian Yu", "Nan Du", "Izhak Shafran", "Karthik Narasimhan", "Yuan Cao"],
    publishedAt: new Date("2022-10-06"),
    pdfUrl: "https://arxiv.org/pdf/2210.03629",
    categories: ["cs.CL", "cs.AI", "cs.LG"],
  },
  {
    arxivId: "2212.04356",
    title: "Robust Speech Recognition via Large-Scale Weak Supervision (Whisper)",
    summary: "We study the capabilities of speech processing systems trained simply to predict large amounts of transcripts of audio on the internet. We show that the combination of large-scale weak supervision enables models that generalize well to standard benchmarks and approach the robustness of human speech recognition.",
    authors: ["Alec Radford", "Jong Wook Kim", "Tao Xu", "Greg Brockman", "Christine McLeavey", "Ilya Sutskever"],
    publishedAt: new Date("2022-12-06"),
    pdfUrl: "https://arxiv.org/pdf/2212.04356",
    categories: ["eess.AS", "cs.CL"],
  },
  {
    arxivId: "2305.10601",
    title: "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
    summary: "We introduce Tree of Thoughts (ToT), a framework that generalizes over chain-of-thought prompting and enables exploration over coherent units of text (thoughts) that serve as intermediate steps toward solving a problem. ToT allows LMs to perform deliberate decision making by considering multiple different reasoning paths and self-evaluating choices.",
    authors: ["Shunyu Yao", "Dian Yu", "Jeffrey Zhao", "Izhak Shafran", "Thomas L. Griffiths", "Yuan Cao", "Karthik Narasimhan"],
    publishedAt: new Date("2023-05-17"),
    pdfUrl: "https://arxiv.org/pdf/2305.10601",
    categories: ["cs.CL"],
  },
  {
    arxivId: "2305.14314",
    title: "QLoRA: Efficient Finetuning of Quantized LLMs",
    summary: "We present QLoRA, an efficient finetuning approach that reduces memory usage enough to finetune a 65B parameter model on a single 48GB GPU while preserving full 16-bit finetuning task performance. QLoRA backpropagates gradients through a frozen, 4-bit quantized pretrained language model into Low Rank Adapters.",
    authors: ["Tim Dettmers", "Artidoro Pagnoni", "Ari Holtzman", "Luke Zettlemoyer"],
    publishedAt: new Date("2023-05-23"),
    pdfUrl: "https://arxiv.org/pdf/2305.14314",
    categories: ["cs.LG"],
  },
  {
    arxivId: "2304.02643",
    title: "Segment Anything (SAM)",
    summary: "We introduce the Segment Anything project: a new task, model, and dataset for image segmentation. Using our efficient model in a data collection loop, we built the largest segmentation dataset to date (by far), with over 1 billion masks on 11 million licensed and privacy respecting images. The model is designed and trained to be promptable, so it can transfer zero-shot to new image distributions and tasks.",
    authors: ["Alexander Kirillov", "Eric Mintun", "Nikhila Ravi", "Hanzi Mao", "Chloe Rolland", "Laura Gustafson", "Tete Xiao", "Spencer Whitehead", "Alexander C. Berg", "Wan-Yen Lo", "Piotr Dollár", "Ross Girshick"],
    publishedAt: new Date("2023-04-05"),
    pdfUrl: "https://arxiv.org/pdf/2304.02643",
    categories: ["cs.CV"],
  },
  {
    arxivId: "2304.08485",
    title: "Visual Instruction Tuning (LLaVA)",
    summary: "We present LLaVA, the first attempt to use language-image instruction-following data generated by GPT-4 for visual instruction tuning. We show that multimodal instruction tuning with GPT-4 generated data results in impressive multimodal capabilities. LLaVA demonstrates impressive chat abilities and achieves SoTA on Science QA with a GPT-4 collaboration approach.",
    authors: ["Haotian Liu", "Chunyuan Li", "Qingyang Wu", "Yong Jae Lee"],
    publishedAt: new Date("2023-04-17"),
    pdfUrl: "https://arxiv.org/pdf/2304.08485",
    categories: ["cs.CV", "cs.CL", "cs.AI"],
  },
  {
    arxivId: "2308.12950",
    title: "Code Llama: Open Foundation Models for Code",
    summary: "We release Code Llama, a family of large language models for code based on Llama 2 providing state-of-the-art performance among open models, infilling capabilities, support for large input contexts, and zero-shot instruction following ability for programming tasks. We provide multiple flavors to cover a wide range of applications: foundation models, Python specializations, and instruction-following models.",
    authors: ["Baptiste Rozière", "Jonas Gehring", "Fabian Gloeckle", "Sten Sootla", "Itai Gat", "Xiaoqing Ellen Tan", "Yossi Adi", "Jingyu Liu", "Tal Remez", "Jérémy Rapin", "Artyom Kozhevnikov", "Ivan Evtimov", "Joanna Bitton", "Manish Bhatt", "Cristian Canton Ferrer", "Aaron Grattafiori", "Wenhan Xiong", "Alexandre Défossez", "Jade Copet", "Faisal Azhar", "Hugo Touvron", "Louis Martin", "Nicolas Usunier", "Thomas Scialom", "Gabriel Synnaeve"],
    publishedAt: new Date("2023-08-24"),
    pdfUrl: "https://arxiv.org/pdf/2308.12950",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2403.08295",
    title: "Gemma: Open Models Based on Gemini Research and Technology",
    summary: "We introduce Gemma, a family of lightweight, state-of-the-art open models built from research and technology used to create Google Gemini models. Gemma models demonstrate strong performance across academic benchmarks for language understanding, reasoning, and safety while being small enough to be deployed in environments with limited resources.",
    authors: ["Gemma Team Google"],
    publishedAt: new Date("2024-03-13"),
    pdfUrl: "https://arxiv.org/pdf/2403.08295",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2404.14219",
    title: "Phi-3 Technical Report: A Highly Capable Language Model Locally on Your Phone",
    summary: "We introduce phi-3-mini, a 3.8 billion parameter language model trained on 3.3 trillion tokens, whose overall performance, as measured by both academic benchmarks and internal testing, rivals that of models such as Mixtral 8x7B and GPT-3.5, despite being small enough to be deployed on a phone.",
    authors: ["Marah Abdin", "Sam Ade Jacobs", "Ammar Ahmad Awan", "Jyoti Aneja", "Ahmed Awadallah", "Hany Awadalla", "Nguyen Bach", "Amit Bahree", "Arash Bakhtiari", "Harkirat Behl"],
    publishedAt: new Date("2024-04-22"),
    pdfUrl: "https://arxiv.org/pdf/2404.14219",
    categories: ["cs.CL", "cs.AI"],
  },
  {
    arxivId: "2407.21783",
    title: "The Llama 3 Herd of Models",
    summary: "Modern artificial intelligence (AI) systems are powered by foundation models. This paper presents a new set of foundation models, called Llama 3. It is a herd of language models that natively support multilinguality, coding, reasoning, and tool usage. Our largest model is dense transformer with 405B parameters and a context window of up to 128K tokens.",
    authors: ["Abhimanyu Dubey", "Abhinav Jauhri", "Abhinav Pandey", "Abhishek Kadian", "Ahmad Al-Dahle", "Aiesha Letman", "Akhil Mathur", "Alan Schelten", "Amy Yang", "Angela Fan"],
    publishedAt: new Date("2024-07-31"),
    pdfUrl: "https://arxiv.org/pdf/2407.21783",
    categories: ["cs.AI", "cs.CL"],
  },
  {
    arxivId: "2412.19437",
    title: "DeepSeek-V3 Technical Report",
    summary: "We present DeepSeek-V3, a strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token. DeepSeek-V3 achieves the best performance among open-source models and rivals the most advanced closed-source models at a fraction of the training cost.",
    authors: ["DeepSeek-AI"],
    publishedAt: new Date("2024-12-26"),
    pdfUrl: "https://arxiv.org/pdf/2412.19437",
    categories: ["cs.CL", "cs.AI", "cs.LG"],
  },
];

export async function seedMustReadPapers(): Promise<number> {
  let added = 0;

  for (const paper of MUST_READ_PAPERS) {
    const exists = await prisma.paper.findUnique({
      where: { arxivId: paper.arxivId },
    });
    if (exists) continue;

    await prisma.paper.create({
      data: {
        ...paper,
        qualityScore: 1.0,
        qualityReason: "Must-read — foundational paper widely praised by the AI community.",
      },
    });
    added++;
  }

  return added;
}
